### PR TITLE
Parameterize executor

### LINKED ISSUE #2: [Enhancement] Parameterize executor.
Suggestion from best practice guideline. Consider parameterizing the docker image or tag to protect against potential sudden changes to the hardcoded docker tag.

https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L49

You may also be interested in using CircleCI's new beta images which are highly optimized for speed. https://hub.docker.com/u/cimg

_Consider adding the `orbtoberfest` label on this issue to have it appear on our upcoming Hacktoberfest landing page_

### PR DESCRIPTION
**Pull request by lex111**
Closes #2

### CODE REVIEW

**Comment by gmoore** [comment]
@lex111 Thanks! Are there are docs to update for these two new parameters?

**Comment by lex111** [comment]
@gmoore A table with parameters will automatically be added to the [registry](https://circleci.com/orbs/registry/orb/contrastsecurity/verify#executors-default), if I understood correctly, did you mean this?

**Comment by gmoore** [comment]
Yeah that's what I meant. I didn't know if there was an extra step to make that happen.

**Comment by lex111** [comment]
It is enough to make a new release and the information will be updated automatically.

**Comment by lex111** [comment]
friendly ping @gmoore, can you merge this PR? It's good for you?

**Pull request merged**
